server:
  port: 8090  

spring:
  application:
    name: micro-auth
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=BDUsers;encrypt=true;trustServerCertificate=true;
    username: sa
    password: sqlserver
  jpa:
    hibernate:
      ddl-auto: none
    database: sqlserver
    database-platform: org.hibernate.dialect.SQLServerDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka