server:
  port: 8761

spring:
  application:
    name: micro-eureka
  config:
    import: optional:configserver:htpp://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      default-zone: http://localhost:${server.port}/eureka/
